#ifndef RAIDSTREAM_ALGORITHMEXPERIMENTALTRIPLEPARITY_HPP
#define RAIDSTREAM_ALGORITHMEXPERIMENTALTRIPLEPARITY_HPP


class AlgorithmExperimentalTripleParity {

};


#endif //RAIDSTREAM_ALGORITHMEXPERIMENTALTRIPLEPARITY_HPP
